[advisories]
ignore = [ ]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
