use std::{io::Write, process::ExitCode};

use clap::Parser;
use oxrdf::graph::{CanonicalizationAlgorithm, CanonicalizationHashAlgorithm};

#[derive(Parser)]
#[command(version, about)]
struct Args {
    #[arg(value_name = "URL")]
    target: url::Url,

    #[arg(long, short = 'c')]
    canonicalize: bool,
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<ExitCode, Box<dyn std::error::Error>> {
    tracing_subscriber::fmt::init();

    let args = Args::parse();
    let client = reqwest::Client::new();
    let base = args.target.to_string();
    let base_iri = oxiri::Iri::parse(base.clone())?;
    let response = client.get(args.target).send().await?.error_for_status()?;
    let content_type = response
        .headers()
        .get(reqwest::header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok());

    if content_type.is_some_and(|ct| !ct.starts_with("text/html")) {
        eprintln!("Error: content type is not text/html.");
        return Ok(ExitCode::FAILURE);
    }

    drop(client);

    let final_url = response.url().clone();

    let content = response.text().await?;
    let mut output_graph = oxrdf::Graph::new();
    let mut processor_graph = oxrdf::Graph::new();
    html2rdf::process(
        &content,
        base_iri.clone(),
        &mut output_graph,
        &mut processor_graph,
    )?;

    {
        // output any warnings/errors
        let serializer = oxttl::TurtleSerializer::new();
        let mut locked_err = std::io::stderr().lock();
        let mut writer = serializer.for_writer(&mut locked_err);
        for triple in processor_graph.iter() {
            writer.serialize_triple(triple)?;
        }

        writer.finish()?;
        drop(processor_graph);
    }

    {
        // use serializer with all known prefixes
        let serializer = html2rdf::initial_context_prefixes().mappings().try_fold(
            oxttl::TurtleSerializer::new().with_base_iri(base)?,
            |serializer, (prefix, value)| serializer.with_prefix(prefix, value),
        )?;

        if args.canonicalize {
            output_graph.canonicalize(CanonicalizationAlgorithm::Rdfc10 {
                hash_algorithm: CanonicalizationHashAlgorithm::Sha256,
            });
        }

        let mut locked_out = std::io::stdout().lock();
        locked_out.write_all(
            format!(
                "# generated by html2rdf {} at {:.0} from: {}\n",
                clap::crate_version!(),
                jiff::Timestamp::now(),
                final_url,
            )
            .as_bytes(),
        )?;

        if args.canonicalize {
            locked_out.write_all(b"# (output has been canonicalized)\n")?;
        }

        let mut writer = serializer.for_writer(&mut locked_out);
        for triple in output_graph.iter() {
            writer.serialize_triple(triple)?;
        }

        writer.finish()?;
        drop(output_graph);
    }

    Ok(ExitCode::SUCCESS)
}
